name: ControlDB Deployment
on: workflow_dispatch 
jobs:
    release:      
      runs-on: windows-latest
      steps:
        - name: Checkout code 
          uses: actions/checkout@v3
        - name: Display checkout files and folders
          run: Get-ChildItem ${{github.workspace}} -Recurse
        - name: Azure Login
          uses: Azure/login@v1
          with:
           creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
        - name: Install Azure CLI
          run: |
            Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi
            Start-Process msiexec.exe -ArgumentList '/I AzureCLI.msi /quiet' -NoNewWindow -Wait
        - name: Install SQLPackage
          run: |
            Invoke-WebRequest -Uri https://aka.ms/sqlpackage-msi -OutFile .\SQLPackage.msi
            Start-Process msiexec.exe -ArgumentList '/I SQLPackage.msi /quiet' -NoNewWindow -Wait
        - name: Build and Deploy SQL Database
          uses: Azure/sql-action@v2
          with:
            connection-string: ${{secrets.CONTROLDB_CONNECTIONSTRING}}
            path: ${{github.workspace}}\elt-framework\ControlDB\ELT\Database.sqlproj
            action: 'Publish'
            arguments: '/p:DropPermissionsNotInSource=false /p:BlockOnPossibleDataLoss=false /p:DropRoleMembersNotInSource=false /p:DropObjectsNotInSource=false /p:IgnoreColumnOrder=true /p:IgnorePermissions=true'
        - name: Azure Logout
          run: |
            az logout